alter table EXAMPLE_OUTGOING_DOCUMENTS add constraint FK_EXAMPLE_OUTGOING_DOCUMENTS_ON_FILE foreign key (FILE_ID) references EXAMPLE_FILE(ID);
create index IDX_EXAMPLE_OUTGOING_DOCUMENTS_ON_FILE on EXAMPLE_OUTGOING_DOCUMENTS (FILE_ID);
