alter table EXAMPLE_OUTGOING_DOCUMENTS add constraint FK_EXAMPLE_OUTGOING_DOCUMENTS_ON_LOG foreign key (LOG_ID) references EXAMPLE_REGISTRATION_LOGS(ID);
create index IDX_EXAMPLE_OUTGOING_DOCUMENTS_ON_LOG on EXAMPLE_OUTGOING_DOCUMENTS (LOG_ID);
