alter table EXAMPLE_OUTGOING_DOCUMENTS_FILE_LINK add constraint FK_OUTDOCFIL_ON_OUTGOING_DOCUMENTS foreign key (OUTGOING_DOCUMENTS_ID) references EXAMPLE_OUTGOING_DOCUMENTS(ID);
alter table EXAMPLE_OUTGOING_DOCUMENTS_FILE_LINK add constraint FK_OUTDOCFIL_ON_FILE foreign key (FILE_ID) references EXAMPLE_FILE(ID);
