alter table EXAMPLE_DOC_FILES add constraint FK_EXAMPLE_DOC_FILES_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table EXAMPLE_DOC_FILES add constraint FK_EXAMPLE_DOC_FILES_ON_OUTGOING_DOCUMENTS foreign key (OUTGOING_DOCUMENTS_ID) references EXAMPLE_OUTGOING_DOCUMENTS(ID);
create index IDX_EXAMPLE_DOC_FILES_ON_FILE on EXAMPLE_DOC_FILES (FILE_ID);
create index IDX_EXAMPLE_DOC_FILES_ON_OUTGOING_DOCUMENTS on EXAMPLE_DOC_FILES (OUTGOING_DOCUMENTS_ID);
