alter table EXAMPLE_WORKERS add constraint FK_EXAMPLE_WORKERS_ON_SUB_DIVISION foreign key (SUB_DIVISION_ID) references EXAMPLE_SUB_DIVISION(ID);
create index IDX_EXAMPLE_WORKERS_ON_SUB_DIVISION on EXAMPLE_WORKERS (SUB_DIVISION_ID);
