alter table EXAMPLE_OUTGOING_DOCUMENTS rename column file_id to file_id__u11442 ;
drop index IDX_EXAMPLE_OUTGOING_DOCUMENTS_ON_FILE ;
alter table EXAMPLE_OUTGOING_DOCUMENTS drop constraint FK_EXAMPLE_OUTGOING_DOCUMENTS_ON_FILE ;
alter table EXAMPLE_OUTGOING_DOCUMENTS add column FILE_ID uuid ;
